### ISSUE TITLE
Setting prior on derived parameter

### ISSUE THREAD

**Issue by LisaGoh** [joezuntz/cosmosis#29]
Hi! 

I am trying to compare likelihood analysis results between some fiducial pipeline with a modified version of CLASS that I have developed. However there is a small difference: in the fiducial pipeline, h0 is a directly sampled parameter with a set prior, while in my version of CLASS it is a derived parameter. 

Hence I'd like to ask if it is possible, somehow, to set a prior condition on the derived H0? For example in my CLASS module, after calculating H0, choosing to discard the point if it falls outside the fiducial prior range.  Like that I can ensure that my pipeline works equivalently to the fiducial pipeline. 

Thank you!

Lisa

**Comment by joezuntz** [comment]
This will work fine provided that you're only looking for parameter constraints, and are not trying to get good Bayesian evidences. Let me know if it's the latter cae and I can have a think.

- for a uniform prior, you could just add a test at the end of your module (or in a new module) whether the H0 value is within the range you want, and if it isn't then `return 1` from the module instead of the usual `return 0`. That will assign zero likehliood to the sample

- if you want a non-uniform prior you could do this at the likelihood level, and add a new single-value likelihood on H0 that matches the prior you want to apply. See the various Riess H0 modules for an example.

- you could also just run without the constraint and apply the prior afterwards at the end of the sample, by removing samples that violate it, or re-weighting them if you want a non-uniform prior.

**Comment by LisaGoh** [comment]
Hi thank you for your prompt reply! I only wish to get parameter constraints, so that's fine. I will try out the methods you suggested.

**Comment by joezuntz** [comment]
Great - I'll close this now, but do re-open it (or other issues) if useful.
