### ISSUE TITLE
Keeping count of module calls

### ISSUE THREAD

**Issue by andrejdvornik** [joezuntz/cosmosis#45]
I would like to know if there is a way in cosmosis to keep track of how many times a module was called for instance when running a sampler? Is there perhaps an iteration number stored somewhere in the data block?

I am asking this because I would like to call the part of an execute function only at certain times, as it is computationally really costly to do so at every step in the sampler. The number of calls would be useful in such case, as then a part of the code could be simply evaluated every n-steps, and otherwise use a cached method.

**Comment by joezuntz** [comment]
No sampling information is currently stored in the datablock. I'm not sure how well the numbers there generalize to different samplers, but I will think about this.

Are you sure you want to do caching based on the position in the chain, rather than the parameter values themselves? The chain won't move a consistent distance between slow executions in this case.  Also you'll have to think carefully about parallelization.

But if you'd like to try then the simplest way to do this is in your case is to store this information in the `config` variable returned by the `setup` function. If you modify the contents of this variable (not redefining the variable I mean like setting a value in a dict or list) then it will be maintained between calls.  e.g.


```
def setup(options):
    config = {}
    # ... 
    # other setup stuff here filling in config dict
    # ...
    config['num_calls'] = 0
    config['cached_slow_info'] = None
    return config

def execute(block, config):
    num_calls = config['num_calls']

    # main part
    if num_calls % 10 == 0:
        # replace value of config['cached_slow_info']
        do_slow_calc()
    else:
        # use current value of config['cached_slow_info']
        do fast_calc()

    config['num_calls'] = num_calls + 1

    return 0
```

Similarly if your setup function returns a class or other object you can store the info there.

Also, depending on your problem and parameter space you might also find this feature helpful:
https://cosmosis.readthedocs.io/en/latest/features/sampler_features.html#fast-slow-sampling

I'll close this for now since hopefully I've answered your question, but please do re-open if you'd like to ask or discuss more.

**Comment by andrejdvornik** [comment]
This is perfect! Thank you!

**Comment by andrejdvornik** [comment]
Coming back to this, as it is somewhat related. It is more of an implementation question, that I cannot see an answer myself from the code.

When caching in this form is performed, is the state shared between different processes or does the cosmosis create a deep copy of everything returned by the `setup` for each process when running a sampler for instance?

**Comment by joezuntz** [comment]
Nothing is shared implicitly between processes - each one has its own variable. But it doesn't actually do any copying - under MPI each process must independently call the initialization process for the pipeline and modules. (We suppress any print outs from non-root processes though, to avoid excessive line noise).

**Comment by andrejdvornik** [comment]
Ok, so when setup is called with multiple processes, at the initialisation process, it does that n times (where n is the number of processes requested), and not necessarily just once as suggested by the print out.

**Comment by joezuntz** [comment]
Yes - exactly.  If you want to see the output from all of the processes for any reason (e.g. debugging) then you can put the `pool_stdout` option in the `runtime` section of the file.  Or you can write to standard error instead, that doesn't get silenced.

```
[runtime]
pool_stdout = T
```

**Comment by andrejdvornik** [comment]
Got it, perfect! This is exactly what I needed to hear. :)
