### ISSUE TITLE
Installation issues on cluster using conda-forge 

### ISSUE THREAD

**Issue by nebblu** [joezuntz/cosmosis#69]
Just leaving this here as it might help others. 

I ran into the two following two issues when attempting to install on the Edinburgh Cuillin cluster using the "Conda-Forge (existing installation)" : 

1.  The first error occurred when I attempted to run "source cosmosis-configure" which resulted in the following error: 

> configure.py: error: unrecognized arguments: viminfo=NONE 

This was solved by running the following command "source cosmosis-configure --source SOURCE" . 

2. The second error related to the compiling of EuclidEmulator2. 

> src/euclidemu2.cpp:488:62: error: invalid use of incomplete type 'PyFrameObject' {aka 'struct _frame'}

This was solved by downgrading python 11 to 10 in the "conda create -p ./env -c conda-forge cosmosis cosmosis-build-standard-library "numpy<1.24"" command: 

> conda create -p ./env -c conda-forge python=3.10  cosmosis cosmosis-build-standard-library "numpy<1.24" 

Hope this helps someone :)

**Comment by joezuntz** [comment]
Hi @nebblu,

Thanks so much for sharing these!

I've seen the first issue before - it means that your login shell is being launched with some arguments to it instead of just nothing. If you do `echo $1` you'll see it there. These get passed whenever you source something with no arguments because bash has a truly weird rule about that.

Cheers,
Joe
